export {LargeTitle} from './LargeTitle/LargeTitle'
export {TitleFirst} from './TitleFirst/TitleFirst'
export {TitleSecond} from './TitleSecond/TitleSecond'
export {Subtitle} from './Subtitle/Subtitle'
export {Body} from './Body/Body'
export {Text} from './Text/Text'
export {Capture} from './Capture/Capture'
export {Footnote} from './Footnote/Footnote'